version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "80:80"
    restart: always
    volumes:
      - ./assets/css:/usr/share/nginx/html/assets/css
      - ./assets/image/logos:/usr/share/nginx/html/assets/image/logos
    networks:
      - db
      - auth
      - gar

networks:
  db:
    external:
      name: db_default
  auth:
    external:
      name: auth_default
  gar:
    external:
      name: gar_default